# Generated by Django 4.1 on 2022-08-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[('available', 0), ('action_required', 1), ('action_in_progress', 2)])),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.model')),
            ],
        ),
    ]
