# Generated by Django 4.1 on 2022-08-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_brand_created_at_brand_name_brand_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='models',
        ),
        migrations.RemoveField(
            model_name='model',
            name='vehicles',
        ),
        migrations.AddField(
            model_name='model',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.model'),
            preserve_default=False,
        ),
    ]
