# Generated by Django 4.1 on 2022-08-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_alter_brand_created_at_alter_brand_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='legal_identifier',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
